added login and registration page
BuildForSDGCohort2/Team-236-Group-A-frontend pull request #5
Opened 2020-09-07 17:54 UTC by kryzbone

2020-09-08 01:03 UTC, mickeymond submitted a review, later dismissed

2020-09-09 17:59 UTC, mickeymond submitted a review, later dismissed
Nice

2020-09-10 07:46 UTC, narteysarso requested changes
Kindly resolve the Codacy quality review issues.

2020-09-12 10:20 UTC, narteysarso submitted a review, later dismissed

2020-09-14 16:45 UTC, mickeymond approved these changes

2020-09-15 11:41 UTC, merged